Build basic cicd (#1)
* fix(): right secrets

* add templates

* add debugging

* change to right name

* add to todo list

* change to work per env

* first try

* try 2

* remove github token

* feat(): try to fix the errors

* remove github token because its default

* try another changes to fix the error

* remove the secrets

* remove github token

* remove claude mistakes

* debugging

* add more debug

* remove sha

* add option to not dev/main && enter the the vars as inputs

* made a few changes. make the pipeline much simplier with env variables

* the env variables are not required

* change to right health path

* change and remove development changes

* change to dewploy aks and not acr

* docs(): fix readme

* docs(): correct the dockerifle

* chore(): move the exaple file to right place

---------

Co-authored-by: adamgur <adamgurevitz1@gmail.com>

diff --git a/.github/workflows/build.docker.yml b/.github/workflows/build.docker.yml
--- a/.github/workflows/build.docker.yml
+++ b/.github/workflows/build.docker.yml
@@ -1,55 +1,92 @@
-# This workflow will build and push an application to a Azure Kubernetes Service (AKS) cluster when you push your code
-#
-# This workflow assumes you have already created the target AKS cluster and have created an Azure Container Registry (ACR)
-# The ACR should be attached to the AKS cluster
-# For instructions see:
-#   - https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough-portal
-#   - https://docs.microsoft.com/en-us/azure/container-registry/container-registry-get-started-portal
-#   - https://learn.microsoft.com/en-us/azure/aks/cluster-container-registry-integration?tabs=azure-cli#configure-acr-integration-for-existing-aks-clusters
-#   - https://github.com/Azure/aks-create-action
-#
-# To configure this workflow:
-#
-# 1. Set the following secrets in your repository (instructions for getting these can be found at https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-cli%2Clinux):
-#    - AZURE_CLIENT_ID
-#    - AZURE_TENANT_ID
-#    - AZURE_SUBSCRIPTION_ID
-#
-# 2. Set the following environment variables (or replace the values below):
-#    - AZURE_CONTAINER_REGISTRY (name of your container registry / ACR)
-#    - RESOURCE_GROUP (where your cluster is deployed)
-#    - CLUSTER_NAME (name of your AKS cluster)
-#    - CONTAINER_NAME (name of the container image you would like to push up to your ACR)
-#    - IMAGE_PULL_SECRET_NAME (name of the ImagePullSecret that will be created to pull your ACR image)
-#    - DEPLOYMENT_MANIFEST_PATH (path to the manifest yaml for your deployment)
-#
-# For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
-# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
-# For more options with the actions used below please refer to https://github.com/Azure/login
-
 name: Build and Push to ACR
 
 on:
-  workflow_call:  # Makes this workflow reusable
-
-env:
-  IMAGE_TAG: ${{ vars.IMAGE_TAG }}
+  workflow_call:
+    inputs:
+      image_name:
+        required: true
+        type: string
+        description: 'Name of the Docker image (e.g., your-repo-name)'
+      image_tag: 
+        required: true
+        type: string
+        description: 'Dynamic tag for the Docker image (e.g., dev, stable)'
+      acr_registry: 
+        required: false
+        type: string
+        description: 'Name of your container registry / ACR (if not provided, will auto-detect)'
+      acr_resource_group: 
+        required: false
+        type: string
+        description: 'Resource group where your ACR is deployed (if not provided, will auto-detect)'
+    secrets:
+      AZURE_CLIENT_ID:
+        required: true
+      AZURE_TENANT_ID:
+        required: true
+      AZURE_SUBSCRIPTION_ID:
+        required: true
 
 jobs:
   build-and-push:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout Repository
+        uses: actions/checkout@v4
       
       - name: Azure Login
-        uses: azure/login@v1.4.6
+        uses: azure/login@v1
         with:
           client-id: ${{ secrets.AZURE_CLIENT_ID }}
           tenant-id: ${{ secrets.AZURE_TENANT_ID }}
           subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
+      - name: Get ACR information
+        id: acr_info
+        run: |
+          set -e
+          
+          # Use provided ACR info or auto-detect
+          if [[ -n "${{ inputs.acr_registry }}" ]]; then
+            ACR_NAME="${{ inputs.acr_registry }}"
+            ACR_RESOURCE_GROUP="${{ inputs.acr_resource_group }}"
+          else
+            # Auto-detect ACR (assumes only one ACR in the subscription)
+            ACR_NAME=$(az acr list --query '[0].name' -o tsv)
+            ACR_RESOURCE_GROUP=$(az acr list --query '[0].resourceGroup' -o tsv)
+          fi
+          
+          if [[ -z "$ACR_NAME" ]]; then
+            echo "Error: No ACR found and none provided in inputs"
+            exit 1
+          fi
+          
+          echo "acr_name=$ACR_NAME" >> $GITHUB_OUTPUT
+          echo "acr_resource_group=$ACR_RESOURCE_GROUP" >> $GITHUB_OUTPUT
+          
+          echo "=== ACR BUILD INFO ==="
+          echo "ACR Name: $ACR_NAME"
+          echo "ACR Resource Group: $ACR_RESOURCE_GROUP"
+          echo "Image Name: ${{ inputs.image_name }}"
+          echo "Image Tag: ${{ inputs.image_tag }}"
+      
       - name: Build and push to ACR
         run: |
-          az acr build --image ${{ vars.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ github.event.repository.name }}:${{ env.IMAGE_TAG }} \
-                       --registry ${{ vars.AZURE_CONTAINER_REGISTRY }} \
-                       -g ${{ vars.RESOURCE_GROUP }} .
+          set -e
+          
+          ACR_NAME="${{ steps.acr_info.outputs.acr_name }}"
+          ACR_RESOURCE_GROUP="${{ steps.acr_info.outputs.acr_resource_group }}"
+          FULL_IMAGE_NAME="${ACR_NAME}.azurecr.io/${{ inputs.image_name }}:${{ inputs.image_tag }}"
+          
+          echo "Building and pushing image: $FULL_IMAGE_NAME"
+          
+          # Build and push using ACR build (which handles authentication automatically)
+          az acr build \
+            --image "$FULL_IMAGE_NAME" \
+            --registry "$ACR_NAME" \
+            --resource-group "$ACR_RESOURCE_GROUP" \
+            --file Dockerfile \
+            .
+          
+          echo "✅ Build completed successfully!"
+          echo "Image available at: $FULL_IMAGE_NAME"
